ccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccc	Common file

      integer ndim, ncomp, ldxgiven
      integer iqtint, ndim_tmp
      double precision unitiny

      common /qtint/ iqtint
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

ccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccc  Incl. relevant files	
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccc   integration specific parameters  
      parameter (ndim_tmp = 4)      

ccc   number of integration components
      parameter (ncomp = 1)
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
      
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
